name: Dv CMenu
author: dvorkin
category: Interface
tags: [interface]
docs: http://dv.tibbo.com/dv_cmenu/README.md
demo: http://dv.tibbo.com/dv_cmenu/Docs/demo.html
current: 1.0

authors:
 - Dvorkin Dmitry
